---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-"
)
# just to keep the code clean below
suppressWarnings(suppressPackageStartupMessages(library(dplyr)))
```

# Global Short-Term Forecasting of Covid-19 Cases

## Abstract

The continuously growing number of COVID-19 cases pressures healthcare services worldwide. Accurate short-term forecasting is thus vital to support country-level policy making. The strategies adopted by countries to combat the pandemic vary, generating different uncertainty levels about the actual number of cases. Accounting for the hierarchical structure of the data and accommodating extra-variability is therefore fundamental. We introduce a new modelling framework to describe the course of the pandemic with great accuracy, and provide short-term daily forecasts for every country in the world. We show that our model generates highly accurate forecasts up to six days ahead, and use estimated model components to cluster countries based on recent events. We introduce statistical novelty in terms of modelling the autoregressive parameter as a function of time, increasing predictive power and flexibility to adapt to each country. Our model can also be used to forecast the number of deaths, study the effects of covariates (such as lockdown policies), and generate forecasts for smaller regions within countries. Consequently, it has strong implications for global planning and decision making. We constantly update forecasts and make all results freely available to any country in the world through an online Shiny dashboard.

## Reproducibility and Replicability in Science

Making data and code available as supplementary material promotes transparency and reproducibility, enabling anyone to analyze data, reproduce our findings, and improve the methodology. 

## Shiny app

A dashboard shiny app can be found in https://prof-thiagooliveira.shinyapps.io/COVIDForecast/

# Contacts

* Thiago de Paula Oliveira - email: thiago.paula.oliveira@usp.br
* Rafael de Andrade Moral - email: rafael.deandrademoral@mu.ie







